name: Daily Commit Bot

on:
  schedule:
    - cron: '0 0 * * *' # Her gün gece 12'de çalıştır
  workflow_dispatch: # Manuel olarak da çalıştırabilmek için

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Python Ortamını Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Gün
